### ISSUE TITLE
do_not_skip ignores paths_ignore

### ISSUE THREAD

**Issue by trombik** [fkirc/skip-duplicate-actions#105]
I have a workflow that builds code. I do not want to build code when the changes are only made on documentation. the following configuration does not skip the build when pull request triggers.

```console
Run fkirc/skip-duplicate-actions@v3.4.0
  with:
    concurrent_skipping: same_content
    paths_ignore: ["docs/**", "**/*.md", "*.md"]
    do_not_skip: ["workflow_dispatch", "schedule", "pull_request"]
    github_token: ***
    paths: []
    cancel_others: false
    skip_after_successful_duplicate: true
Do not skip execution because the workflow was triggered with 'pull_request'
```

it seems that `do_not_skip` has a higher priority than `paths_ignore`. is this a feature?

**Comment by fkirc** [comment]
> it seems that `do_not_skip` has a higher priority than `paths_ignore`. is this a feature?

Yes, that's the current Implementation of do_not_skip.

**Comment by trombik** [comment]
closing because it is not a bug, but a feature.

however, it would be nice if the action outputs various state of the commit ref, instead of implementing the logic itself, such as `same_content = true`, `changed_files = []`, etc.

**Comment by fkirc** [comment]
I agree, I have already considered to expand the number of outputs such that more logic can be added without changing the Action itself.
Perhaps we could merge a PR with more outputs.
