### ISSUE TITLE
Create a "v3" tag that points at the latest v3 release

### ISSUE THREAD

**Issue by RebeccaStevens** [fkirc/skip-duplicate-actions#126]
Would you be able to create a v3 tag that is the same as the latest v3 release (currently v3.4.0)?
Then whenever a new minor/patch version is released, update that tag to point to that new release?

This will allow for simply using:

```yaml
uses: fkirc/skip-duplicate-actions@v3
```

To use the latest release.

This is how the actions in https://github.com/actions work.

**Comment by fkirc** [comment]
I have now pushed both a v3-tag and a v3.4.1-tag
