### ISSUE TITLE
Matched paths as output

### ISSUE THREAD

**Issue by bulseeyeLF** [fkirc/skip-duplicate-actions#139]
Hey, first of all, awesome action! :fire:

Is it possible to add a separate output that would output files that matched the filters (`path` option)?

Additionally, maybe add smlr support as in https://github.com/dorny/paths-filter for naming the filters

Suggesting as my use case is:
Monorepo with different services and I want this action to run on any service files change, but the above mentioned output of matched filters would be passed as a matrix input (JSON Array) to the next job that would run unit tests for all changed services

Thanks

**Comment by fkirc** [comment]
Hi,

Outputting matched files sounds doable; I would be willing to merge a PR that adds this feature.

**Comment by bulseeyeLF** [comment]
Thank you very much :) how about named filters? 👼

**Comment by fkirc** [comment]
I would look into a PR, I guess that its best to output almost everything
