### ISSUE TITLE
Github Support Removal of a PR for sensitive content causes all subsequent runs of this action to fail

### ISSUE THREAD

**Issue by emabrey** [fkirc/skip-duplicate-actions#140]
Github support was requested to delete a PR in our tenacityteam/tenacity repository. This action was successfully run on that PR before the PR was deleted. Now, after that deletion, whenever any PR, scheduled run, manual workflow dispatch, etc. attempts to run this action, it fails with the error `Could not find the tree hash of run [object Object]`.

Please see https://github.com/tenacityteam/tenacity/runs/3626205786?check_suite_focus=true for an example.

**Comment by gaius-qi** [comment]
You can use `ignore-path`

**Comment by paescuj** [comment]
This might have been fixed by #178.

**Comment by paescuj** [comment]
Closing this issue as it is very likely that it has been fixed by #178. Please open a new issue if there is still a problem.
