### ISSUE TITLE
Export information about the run that skips the current run

### ISSUE THREAD

**Issue by Makeshift** [fkirc/skip-duplicate-actions#141]
Suggestion: Export information such as the build number, SHA hash, etc. of the run that superseded the current one that is being skipped. The run number is already logged out, eg. https://github.com/fkirc/skip-duplicate-actions/blob/master/src/index.ts#L205, but this isn't accessible as part of the workflow.

A common workflow involves building containers, testing those containers, then promoting those containers.

In the case of a merge commit with skip-duplicate-actions, we don't want to rebuild containers that have already been built/tested, so in the case of a `shouldSkip: true` we'd like to pull down the containers of the run that succeeded already, retag them with the SHA hash of the current workflow and push them, so it would be nice if `skip-duplicate-actions` could export information about the commit.

I did try to implement this myself so I could PR it, but I'm unfamiliar with TS and just end up with an uncomfortably large number of errors if I try to build :(

**Comment by fkirc** [comment]
Thanks for your suggestions; I agree that more outputs could be helpful, therefore this issue is up for grabs.
I guess that this will work similar to the `should_skip`-output.
