### ISSUE TITLE
Warning: Failed to cancel previous runs due to permission

### ISSUE THREAD

**Issue by jneira** [fkirc/skip-duplicate-actions#149]
* From https://github.com/fkirc/skip-duplicate-actions/issues/103 as i think the issue continue being reproduced

* With a [workflow ](https://github.com/haskell/haskell-language-server/actions/runs/1398445950/workflow)including this permission
```
permissions:
  actions: write
  pull-requests: write
```
* And setting write permission for actions in the project settings
* The action fails to cancell previous runs:

https://github.com/haskell/haskell-language-server/runs/4045146716?check_suite_focus=true

I suspect it happens if the pr is from a fork (nd most of them are in our case :worried: )

As stated in the previous issue you can do it using directly the workflow option: https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#example-using-concurrency-to-cancel-any-in-progress-job-or-run but if you want to keep using this action you have two ways for doing the same, one of them not working. I would prefer keep only this action and not add the new workflow option.

**Comment by paescuj** [comment]
A late answer, but maybe still helpful...

> I suspect it happens if the pr is from a fork (nd most of them are in our case 😟 )

This is exactly the case! For security reasons, workflows triggered on `pull_request` from external forks do not have write permissions on the target repository.

If your workflow does **not** include any dangerous processing (e.g. building or running the content of the PR) you might be able to overcome this limitation by using the trigger `pull_request_target` instead (which has write permission to the target repository).
However, please take extra care when using this trigger! There's a good article which explains the difference between those two triggers and when/how they can be used in a safe manner: https://securitylab.github.com/research/github-actions-preventing-pwn-requests/

If your workflow does not allow the use of `pull_request_target` for security reasons, I think that using the built-in [concurrency](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency=) option is the only (albeit a good) way.
