### ISSUE TITLE
Underspecified behaviour of `concurrent_skipping: "always"`

### ISSUE THREAD

**Issue by bobismijnnaam** [fkirc/skip-duplicate-actions#158]
I was wondering about the following situation. Given that `concurrent_skipping` is set to `always`. What if I quickly push 2 commits that build upon eachother to a branch, which emits two push events. Two workflow runs will be queued. Is it then guaranteed that only the newest commit will run, and that the older commit will be cancelled? Or is it possible that the older commit cancels the workflow run of the newer commit?

Unfortunately I am quite sure I need `always`, because of #157, but please correct me if I'm wrong.

It would be fine if the response to this question is, "no, please refrain from pushing commits that quickly", but it would be nice to know about this in advance. I also had a hard time replicating this in our own repo so that's why I'm asking here (sorry if I missed a link to a community chat).

**Comment by fkirc** [comment]
I am not sure about your exact use case, but maybe you can use `same_content_newer` or `do_not_skip`.
The `cancel_others`-features is intended to save resources, but it is not intended to be reliable.
If you want something reliable, then I suggest skipping instead of cancellations.

**Comment by bobismijnnaam** [comment]
Okay, that is a satisfactory answer for me. Thanks for your time.
