### ISSUE TITLE
README should state that json arrays for inputs should be json strings

### ISSUE THREAD

**Issue by bulseeyeLF** [fkirc/skip-duplicate-actions#201]
Proposition:

For all inputs that are JSON-Arrays, specify in the examples that they should be:

example/default: `'["path1", "path2"]'`
vs.
example/default: `["path1", "path2"]`

**Comment by paescuj** [comment]
I was about to submit a pull request for this, but IMHO it looks very weird with all the quotes in the [inputs](https://github.com/fkirc/skip-duplicate-actions#inputs) section...
Actually, this should already be clear from the [Usage examples](https://github.com/fkirc/skip-duplicate-actions#usage-examples), but maybe we could add a note at the top of this section.
What are your thoughts on this @fkirc?

**Comment by fkirc** [comment]
I would agree with @bulseeyeLF that the README should be as similar as possible to the YAML syntax

**Comment by paescuj** [comment]
> I would agree with @bulseeyeLF that the README should be as similar as possible to the YAML syntax

Thanks for your feedback! I must admit that it makes sense, so I've just submitted a corresponding pull request 👍
