### ISSUE TITLE
Understanding the Merge workflow

### ISSUE THREAD

**Issue by viralsavaniIM** [fkirc/skip-duplicate-actions#212]
Hey, @fkirc amazing work on the `skip-duplicate-actions`. 
I am planning to use this action in one of my projects and was trying to understand the behavior of `skip-duplicate-actions` after the merge of a pull request.

This is the action config we are using for the job
```
jobs:
  pre_job:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v3.4.0
        with:
          skip_after_successful_duplicate: 'true'
          do_not_skip: ["pull_request", "schedule"]
```

Consider the situation in the below git history. 
```
                ▲
                │
                │ Merge commit_13
                *<────────────────────────┐
                │                         │
                │                         │
                │                         │
                │                         * commit_12 (no action run)
                │                         │
                │                         │
                │                         * commit_11 (no action run)
                │                         │
  Action Ran    * commit_10               │
Successfully    |─────────────────────────┘
                ┼                      feature/test
  Action Ran    * commit_9             (branch)
Successfully    │
                │
                │
                │
             develop
            (branch)
```

What I want, is to make sure the job runs in the `develop` branch once the PR is merged. The same job most likely would have _not run_ on the `feature/test` branch.

I'm reading the docs and I see

> However, if a merge yields a result that is different from the source branch, then the resulting workflow-run will not be skipped.

But I'm not sure what the action considers `different`.

Thanks for the help.

**Comment by paescuj** [comment]
> What I want, is to make sure the job runs in the `develop` branch once the PR is merged. The same job most likely would have _not run_ on the `feature/test` branch.

Why is the job not running on the `feature/test` branch?

> But I'm not sure what the action considers `different`.

With your current configuration, it means that the job will always run on the `develop` branch after a merge.

I'm having some difficulty to understand what you're trying to accomplish. What are your expectations for `skip-duplicate-actions`?

**Comment by viralsavaniIM** [comment]
`develop` has a workflow that will be triggered by Github ReST API every night. They are very long jobs so we want to make sure that if a commit has already run the workflow, don't need to rerun it.

> Why is the job not running on the feature/test branch?

In the `feature` branch _we do not_ automatically call the nightly workflow (using ReST API) as they are very long-running and it doesn't really need to run on each commit, as `feature` branches have a lot of incremental commits compared to `develop`. Although, if the developer wants to, they can manually schedule the nightly workflow from Actions UI in the repo.

But when the merge to `develop` happens we need to run the workflow, regardless if the workflow was run on the last `develop` or `feature` (that is being merged).

**Comment by paescuj** [comment]
Thank you for the clarification!

> `develop` has a workflow that will be triggered by Github ReST API every night. They are very long jobs so we want to make sure that if a commit has already run the workflow, don't need to rerun it.

Assuming you're using [`workflow_dispatch`](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch) for this, your configuration looks fine. (Since you've not included `workflow_dispatch` in the `do_not_skip` parameter)

> But when the merge to `develop` happens we need to run the workflow, regardless if the workflow was run on the last `develop` or `feature` (that is being merged).

I assume you've configured the trigger for the workflow to something like this:

```yaml
on:
  push:
    branches:    
      - develop
```

Merging a pull request into the `develop` branch results in a `push` event for this branch, like a commit pushed directly to this branch.

So you need to adjust your configuration as follows (`push` instead of `pull_request`):
```yaml
          do_not_skip: ["push", "schedule"]
```

This means the workflow always runs on `push` events on the`develop` branch - be it after a merged pull request or a directly pushed commit. However, I think that's fine, since commits can rarely be skipped anyway.

Does that answer your question?
