### ISSUE TITLE
Is the "step-security" hard fork affiliated with or endorsed by the contributors?

### ISSUE THREAD

**Issue by cameronraysmith** [fkirc/skip-duplicate-actions#339]
There appears to be a hard fork of this repository at https://github.com/step-security/skip-duplicate-actions .

The only remaining references to this repository appear to be:

- https://github.com/step-security/skip-duplicate-actions/blob/9ab30315a4416bbb930a2da2fd20b4cc72dc4e39/src/main.ts#L198
- https://github.com/step-security/skip-duplicate-actions/blob/9ab30315a4416bbb930a2da2fd20b4cc72dc4e39/src/main.ts#L530

There is one previous interaction with a bot account https://github.com/step-security-bot here https://github.com/fkirc/skip-duplicate-actions/issues/233 .

Is this ["step-security" hard fork](https://github.com/step-security/skip-duplicate-actions) affiliated with or endorsed by the previous contributors to [fkirc/skip-duplicate-actions](https://github.com/fkirc/skip-duplicate-actions)?

**Comment by fkirc** [comment]
Hi, until now I have never heard about the step-security hardfork, so there does not exist any kind of affiliation.

**Comment by cameronraysmith** [comment]
Thank you for confirming fkirc and many thanks for skip-duplicate-actions as well.
