### ISSUE TITLE
Issue, cypress parallel jobs not being marked green.

### ISSUE THREAD

**Issue by joegaudet** [fkirc/skip-duplicate-actions#44]
Hey, tried out your actions, set them up as expected and they seem to work great. However I'm using cypress with parallel runs to speed up testing, and as a result those required checks are not being marked as having passed.

Any thoughts?

![Screen Shot 2020-10-08 at 4 45 22 PM](https://user-images.githubusercontent.com/123911/95524231-a9dc0080-0985-11eb-8463-9d142ff6a070.png)

**Comment by joegaudet** [comment]
I also see these skips here, not sure if they are working to mark the flow green as well.

![Screen Shot 2020-10-08 at 4 46 39 PM](https://user-images.githubusercontent.com/123911/95524296-d728ae80-0985-11eb-85fd-98ef20aedd9d.png)

**Comment by fkirc** [comment]
In my experience, GitHub accepts required checks that have been skipped.
This means that you should be able to merge the PR in your screenshot.
In other words, if your skipping-logic is doing something sane, then you can treat skipped checks as "passed" checks.

**Comment by joegaudet** [comment]
Gotcha, so it works fine for the non parallelized checks, the cypress ones
won't work though, due to the fan out verify (1) verify (2) verify (3)

**Comment by fkirc** [comment]
In general, parallelized checks shouldn't be a problem for this Action.
The newest release contains a `concurrent_skipping` option. If `concurrent_skipping` is set to false, then parallel workflows won't be skipped.

Nevertheless, the `concurrent_skipping` option is more about entire workflows.
If we are talking about individual jobs or steps, then it is doable to place multiple copies of `skip-duplicate-actions` within a single workflow.
Alternatively, a single `pre_job` can be used to skip multiple subsequent jobs.

**Comment by joegaudet** [comment]
This is about steps yeah, it's part of a larger workflow that generates 4
checks, they all need to report passed to github in order for the PR to go
green.

I'll give it a go later today :)

**Comment by fkirc** [comment]
One example that might be helpful is the following Action of GitHub docs: https://github.com/github/docs/blob/main/.github/workflows/test.yml

They have  a rather complex test-setup, and they are using `skip-duplicate-actions` to optimize GitHub's own documentation-workflows.

**Comment by fkirc** [comment]
Perhaps this is the same issue as my problem with "matrix testing": https://github.com/fkirc/skip-duplicate-actions/issues/56
Right now, I believe that one additional `if` per step is needed in order to support "matrix testing".
