### ISSUE TITLE
Improve Support For Matrix Testing

### ISSUE THREAD

**Issue by fkirc** [fkirc/skip-duplicate-actions#56]
`attranslate` uses "matrix-testing" to test Ubuntu, macOS and Windows: https://github.com/fkirc/attranslate
However, supporting "matrix-testing" with `skip-duplicate-actions` seems to be cumbersome.
The screenshot below illustrates the problem.
The workflow is here: https://github.com/fkirc/attranslate/blob/master/.github/workflows/ci.yml
One way to fix it are skip-checks for individual workflow-steps.
This is already doable, but it requires one additional line per step.

![image](https://user-images.githubusercontent.com/17876666/98423828-28fd4b00-2090-11eb-84c2-bfa9b4c08097.png)

**Comment by fkirc** [comment]
After changing the "required checks" to only "ci", the PR is mergeable again:

![image](https://user-images.githubusercontent.com/17876666/98424256-804feb00-2091-11eb-8f1b-411af4af847e.png)


![image](https://user-images.githubusercontent.com/17876666/98424173-37983200-2091-11eb-8734-14e8938f4032.png)

**Comment by haase1020** [comment]
I am running into this issue as well - is there a fix for parallel tests? 
![tests](https://user-images.githubusercontent.com/58481829/106734268-d117a700-65e0-11eb-8e5e-d82a897a7cb2.png)

**Comment by fkirc** [comment]
Right now, the only workaround I am aware of is to skip individual steps (described in README).
This should be doable, but it might lead to quite a lot of boilerplate YAML-code.

**Comment by haase1020** [comment]
That is what I did, and now the pre_job is no longer working....

**Comment by fkirc** [comment]
If you are aiming to skip individual steps, then you might want to delete your pre_job, and instead use a regular step for `skip-duplicate-actions`.
But anyways, I cannot give detailed advise because there are nearly infinite ways to use `skip-duplicate-actions` as a pluggable component.
The README only contains two possible configurations.

**Comment by haase1020** [comment]
It's working - thank you so much!!

**Comment by akd-io** [comment]
I was facing this problem as well and was happy to find this issue! Will give the non-pre-job approach a try.
