### ISSUE TITLE
Unable to get paths_ignore to work as expected

### ISSUE THREAD

**Issue by kpfleming** [fkirc/skip-duplicate-actions#58]
I've just started using this today, after also finding out that the `paths-ignore` filter in GitHub Actions doesn't actually work the way anyone would want it to...

The project repo is here: https://github.com/kpfleming/ansible-pdns-auth-api/tree/ci-rework/.github/workflows

`ci-pr.yml` and `build-image-and-ci-pr.yml` have the same triggers on event types and branches, but different path filters (with no overlap between the specified paths). In addition, any path which triggers `build-image-and-ci-pr.yml` should cause `ci-pr.yml` to *not* be run, as it's either wasteful or will generate false negative results. The goal here is that if a PR touches files in both groups of paths, only the `build-image-and-ci-pr.yml` workflow will be executed.

I've added `skip-duplicate-actions` to `ci-pr.yml`, with `paths_ignore` set to the list of paths which should cause the job to be skipped. This was included in the most recent commit in the PR branch, which also touched one of the 'exclusion' paths. In spite of that, when the `preflight` job ran, it apparently did not return `true`, so the remaining jobs in that workflow were executed.

Is there something I've misunderstood, or should have done differently?

**Comment by fkirc** [comment]
Based on your test-commits, I am not sure about the exact details.

In principle, this Action's `paths_ignore` needs the following preconditions to skip something:

- A commit must only modify files that are matched by `path_ignore`
- There must exist a previous successful workflow-run for the same workflow, and this workflow-run must be exist for a parent-commit of the current commit (not necessarily a direct parent).

**Comment by kpfleming** [comment]
Ahh, OK. That doesn't quite match my requirements then, which explains why it's not doing what I expected :-)

I'll need to find an action which just checks the entire list of files modified in the PR (current commit or any previous one), I think. Thanks for the quick response!

**Comment by kpfleming** [comment]
Looks like dorny/paths-filter will do what I need.

**Comment by fkirc** [comment]
The goal of this Action is to establish a "correctness-proof" based on previously checked commits, because otherwise a safe test-skipping wouldn't be possible (for most projects).

But anyways, I think that there exist other path-filter-Actions that are looking at PR-diffs instead of commit-histories.
