### ISSUE TITLE
GitHub Actions Wishlist

### ISSUE THREAD

**Issue by fkirc** [fkirc/skip-duplicate-actions#60]
This entire project was written in the hope of more features, and some of those features are already discussed in https://github.com/fkirc/skip-duplicate-actions/issues/59.
Nevertheless, it would be nice if GitHub staff like @chrispat had a look at this wishlist.

# Stage 1: Auto-merge once checks are green

I often encounter the situation that I want to merge a PR, but I need to wait a few minutes until tests are green.
This distracts my attention because I need to switch back to the PR when I am already working on a completely unrelated task.
To make this smoother, it would be nice to have an "auto-merge" button that just merges a PR once all "required checks" are green.

# Stage 2: Automated and safe merging of "outdated branches"

Once stage 1 is implemented, I can think of a more sophisticated solution.
Namely, there is a certain risk involved when merging "outdated" branches, because the result of the merge can be different than the branch that was tested by GitHub Actions.
I know that there exists the option to forbid the merge of "outdated PRs", however this option can become rather tedious in a busy environment with lots of small changes on the base-branch.
To make "outdated branches" more convenient without sacrificing safety, I would prefer to have the following automated "merge-algorithm":

- Merge base-branch into feature-branch, such that the PR becomes up-to-date. Then run "required checks" on the feature-branch.
- Once required checks are green, merge the PR without any further user interaction.

**Comment by chrispat** [comment]
Hello @fkirc.  Thank you for taking the time to provide detailed feedback on functionality you would like to see in GitHub.  In looking at this list i think they are more about the overall PR experience than Actions specifically and I know we have seen at least the first part of the feedback from many people before.  

I have passed this feedback on to my colleague who owns the PR experience.

**Comment by fkirc** [comment]
Thank you for your quick response.
Yes, those two items are more about general PR experience in combination with GitHub Actions.
In contrast, the items in #59 are more specific about GitHub Actions.
