### ISSUE TITLE
Allow space-separated strings as inputs

### ISSUE THREAD

**Issue by gagle** [fkirc/skip-duplicate-actions#64]
Instead of this:

```
paths: '["apps/*", "libs/*", "angular.json", "nx.json", "package.json"]'
```

You could do this:

```
paths: >
  apps/*
  libs/*
  angular.json
  nx.json
  package.json
```

Or:

```
paths: apps/* libs/* angular.json nx.json package.json
```

What is you intented purpose for having a json-encoded string as input?

By the way, this action is a hidden gem in the Github Actions community. Good job.

**Comment by fkirc** [comment]
I don't have a specific reason for JSON Strings, but it was the first implementation.
However, this would be hard to change because I don't want to break existing workflows that rely on this action.

**Comment by fkirc** [comment]
But anyways, I would merge a PR that does a simple string-split and remains backwards-compatible, because it shouldn't be more than a few lines of TypeScript.
