### ISSUE TITLE
Comparing commits (base and head refs)

### ISSUE THREAD

**Issue by gagle** [fkirc/skip-duplicate-actions#65]
How can I pass in the base and head refs to allow calculating the diff from 2 arbitrary commits? I'm using a [slash-dispatch-command](https://github.com/peter-evans/slash-command-dispatch) action and I receive the abse and head refs in a repository-dispatch event. I created this action (https://github.com/gagle/changed-directories) some time ago to calculate the diff between 2 commits but it would be great to have all these utilities inside your action. Internally I'm using `octokit.repos.compareCommits()` function but I see that you're not using it, you seem to do a recursive loop, right? Have you checked this function? What is the best approach?

**Comment by fkirc** [comment]
This Action doesn't do a recursive loop, but it does a backtracing from the current commit to previous commits (but not in all cases).
But perhaps https://github.com/dorny/paths-filter might be a better reference for your purposes.
