### ISSUE TITLE
Having trouble setting up correctly

### ISSUE THREAD

**Issue by SirWindfield** [fkirc/skip-duplicate-actions#79]
Hey! I have troubles setting this action up correctly. I think I configured it correctly but the jobs that I specified using the `if`-clause still get all triggered.

Here is the workflow file: https://github.com/Spotifyd/spotifyd/blob/master/.github/workflows/ci.yml
And here is the PR that triggers all steps, even though it should only trigger the `pre_job` one: https://github.com/Spotifyd/spotifyd/pull/743

I've tried to set the action up so it only triggers `codestyle`, `lint` and `check` if files inside of `src/` change or one of the following files: `Cargo.toml`, `Cargo.lock`, `.github/workflows/ci.yml`.

I'd really really appreciate your help, as we are having troubles with protected branches and GitHub's `paths` feature. All our PRs hang and wait for checks :(

**Comment by fkirc** [comment]
Your setup seems to be correct, you have configured the paths feature as expected.
However, this paths feature works very different than GitHub's native paths feature.
I explained the differences to GitHub's native paths feature in https://github.com/fkirc/skip-duplicate-actions/issues/59.

My feeling is that you your repo has very few successful checks that are parents of the commits that you want to path-skip.
If such successful parent-checks cannot be found, then this Action won't path-skip anything.

**Comment by fkirc** [comment]
I have to admit that the logging-situation was bad, which made it hard to see why paths-skipping failed.
Therefore, I published https://github.com/fkirc/skip-duplicate-actions/pull/80 as an attempt to improve the logging-situation.
So if you upgrade to v3.3.0, then you should see exactly why something was skipped or not skipped.
Feel free to re-open the issue if the result is still not understandable with the logging of v3.3.0.

**Comment by SirWindfield** [comment]
That could actually be it! The part that through me off was that the PR that I opened to change the workflow file worked as indented in the first place, it only ran the `pre_job` and nothing else, as it's path wasn't specified inside the array. I then concluded that everything worked correctly without problems.
