### ISSUE TITLE
The logic problem of getBooleanInput

### ISSUE THREAD

**Issue by LarchLiu** [fkirc/skip-duplicate-actions#82]
https://github.com/fkirc/skip-duplicate-actions/blob/4b08373b913cd3d82ae064d16dbb8d90c2970806/src/index.ts#L361

it should be return rawInput.toLowerCase() === 'true';

**Comment by fkirc** [comment]
Thanks for reporting, can you open a PR to fix it?

**Comment by fkirc** [comment]
merged
