### ISSUE TITLE
Force pushing a branch doesn't stop previous runs

### ISSUE THREAD

**Issue by bpinto** [fkirc/skip-duplicate-actions#86]
Build running with Git Tree: `A -> B -> C`
Force push a new tree `A -> B -> D`

This new push doesn't stop the previous tree build even though they are the same branch.

**Comment by paescuj** [comment]
IMO, this should actually work.
Could you share your configuration, if still available?

**Comment by bpinto** [comment]
@paescuj I tested this workflow and it worked.

**Comment by paescuj** [comment]
@bpinto Nice, thank you for reporting back!
