### ISSUE TITLE
Skip duplicate run is not working since last few days

### ISSUE THREAD

**Issue by sounakchatterjee00** [fkirc/skip-duplicate-actions#95]
jobs:
    pre_job: 
        runs-on: ubuntu-latest
        outputs:
          should_skip: ${{ steps.skip_check.outputs.should_skip }}
        steps:
          - id: skip_check
            uses: fkirc/skip-duplicate-actions@master
            with:
              skip_after_successful_duplicate: 'Only skip same content'
    build-deploy-test:   
      needs: pre_job
      if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
      runs-on: [self-hosted, linux, X64]

this is my configuration to avoid duplicate run from the same branch. it was working properly 10 days ago but now with the same configuration, it's not able to find any run to cancel when multiple builds are executing simultaneously in the same branch. would you please look into it ASAP

**Comment by fkirc** [comment]
Hi,
In the last update, I changed the default of `cancel_others` from true to false because of multiple reasons.
Therefore, you will probably need to add `cancel_others: true`.

**Comment by papb** [comment]
@fkirc That was a breaking change, it should have raised the major version according to the semver spec. Can you please release v4.0.0 identical do v3.4.0, and also release v3.4.1 in which that change is reverted? This would be the best way to fix this mistake according to the semver spec.

**Comment by fkirc** [comment]
Sorry about that, I will ensure that semver will be complied with for all future-releases.
